var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(portal)/admindashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__054xg8y._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1qkuvj6.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-z2tje._.js")
R.c("server/chunks/ssr/node_modules_0yjqtz1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bntp-0._.js")
R.c("server/chunks/ssr/app_(portal)_admindashboard_layout_tsx_0yxxo6p._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(portal)_admindashboard_page_actions_18c84gb.js")
R.m(754901)
module.exports=R.m(754901).exports
