// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admindashboard" | "/catalog" | "/clientexample" | "/configurator" | "/dashboard" | "/evora3dstudio" | "/how-it-works" | "/join" | "/kitchen" | "/login" | "/portal" | "/shop" | "/shop/[category]" | "/shop/rooms" | "/showroom" | "/start" | "/studio" | "/v2" | "/v3" | "/visit"
type AppRouteHandlerRoutes = "/api/portal/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admindashboard" | "/catalog" | "/kitchen" | "/shop/rooms" | "/showroom"
type RedirectRoutes = "/pufferweb"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admindashboard": {}
  "/api/portal/[...path]": { "path": string[]; }
  "/catalog": {}
  "/clientexample": {}
  "/configurator": {}
  "/dashboard": {}
  "/evora3dstudio": {}
  "/how-it-works": {}
  "/join": {}
  "/kitchen": {}
  "/login": {}
  "/portal": {}
  "/pufferweb": {}
  "/shop": {}
  "/shop/[category]": { "category": string; }
  "/shop/rooms": {}
  "/showroom": {}
  "/start": {}
  "/studio": {}
  "/v2": {}
  "/v3": {}
  "/visit": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admindashboard": never
  "/catalog": never
  "/kitchen": never
  "/shop/rooms": never
  "/showroom": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
