var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(site)/how-it-works/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12qjua9._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_122yans.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-z2tje._.js")
R.c("server/chunks/ssr/node_modules_0yjqtz1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/[root-of-the-server]__1s5q3o2._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(site)_how-it-works_page_actions_1q5wmvj.js")
R.m(66122)
module.exports=R.m(66122).exports
