/* Map a .jpg/.jpeg/.webp asset path to its .avif sibling. AVIF siblings are
   generated by scripts/to-avif.mjs — only call this where one exists. Pair with
   a <picture> <source> so browsers that can't decode AVIF keep the original. */
export const avifSrc = (src: string) => src.replace(/\.(jpe?g|webp)$/i, ".avif");
